### PR TITLE
Add a rectangle shape for nodes

### PR DESCRIPTION
**Pull request by parleur**
All is in the title, now you can make the node represented by a rectangle or an ellipse, ellipse is still the default configuration. I have coded this as close as your api as I can.

The reason why I've choosen you project, is my need of many export format provided by matplotlib, and the absolute need of support for latex formula.

### CODE REVIEW

**Comment by parleur** [comment]
Hi I don't have rights for merging. Could someone merge for me? Or tell me if I should add/modify something?

**Comment by sammosummo** [comment]
I second merging this. This is the only thing that's currently preventing me using daft.

**Comment by dostodabsi** [comment]
Just stumbled upon daft, and I need rectangular nodes. Is daft still maintained? Why is this pull request not being merged?

**Comment by drphilmarshall** [comment]
Hi Fabian: I think @dfm is on vacation right now, but he'll see this buzz
when he gets back I'm sure. In the meantime, you could consider cloning
@parleur's fork and using the triangle.py code in there directly. I know
it's not ideal, and you'd have to figure out your PYTHONPATH etc, but at
least you'd be able to make the figures you need.  If you already are
working from the base repo (instead of the pip installed code) then you can
just `git remote add parleur git@github.com:parleur/daft.git` and then `git
checkout -b rectangles parleur/master`



On Fri, Jul 31, 2015 at 10:30 AM, Fabian Dablander <notifications@github.com

**Comment by parleur** [comment]
Thank you for merging this very very ... ... very old commit. I didn't expect it any more, but still pleasant to be merged.

**Pull request merged**
